### ISSUE TITLE
decide if we want to change blocks or their definitions for each transition step

### ISSUE THREAD

**Issue by MajeedKazemi** [MajeedKazemi/blocks-to-code#3]
- what are the pros and cons?
- make sure that we consider all the transition steps

**Comment by MajeedKazemi** [comment]
- design how transitions will be stored in the code?
- and how will you activate one of the transition steps?

**Comment by carlkma** [comment]
RE: how transitions will be stored in the code

A huge JSON array:
```
[
{ block: text_print,
  version: 1 },
{ block: loop_while,
  version: 3 },
...
]
```
