### ISSUE TITLE
infinite loop with 'forever' block

### ISSUE THREAD

**Issue by carlkma** [MajeedKazemi/blocks-to-code#9]
Good news: every block is now functional!
Bad news, the forever block, which is essentially `while True:`, is also "functional"

- if not paired with an appropriate 'stop all' block (or `break`), the program goes on an infinite loop

**Comment by carlkma** [comment]
same thing happens when we input an always-false condition for the 'repeat-until' block

**Comment by MajeedKazemi** [comment]
a few suggestions for this:
1. use a `setInterval` timer to execute the code inside the forever block
every 100ms to make it less resource intensive.
2. the "run" button should turn into "stop" when clicked and still execute
the user's code. the forever block could include a code that would break
the while True loop when the stop button is clicked.
